
- name: Ensure base group
  group:
    name: "{{ base_group }}"
    state: present

- name: Ensure base user
  user:
    name: "{{ base_user }}"
    group: "{{ base_group }}"
    state: present

- name: Ensure ajoeph group
  group:
    name: ajoseph
    state: present

- name: Make sure we have a 'ajoseph' user
  user:
    name: ajoseph
    state: present
    group: ajoseph
    groups: "{{ base_group }}"
    append: yes

- name: Make sure we have a 'ajoseph' group
  group:
    name: ajoseph
    state: present

- name: Allow 'ajoseph' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%ajoseph'
    line: '%ajoseph ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Ensure /var/www directory has correct permissions.
  file:
    path: /var/www
    state: directory
    owner: "{{ base_user }}"
    group: "{{ base_group }}"

- name: copying nodejs application with required access
  copy:
    src: /Users/iicuh/personnel/repos/node
    dest: /var/www
    owner: "{{ base_user}}"
    group: "{{ base_group }}"
    mode: 0644
