- name: installing haproxy
  become: yes
  apt:
    name: haproxy
    state: present
- name: setting up haproxy conf file
  template:
    src=haproxy.conf.tbl
    dest=/etc/haproxy/haproxy.conf
  notify: restart haproxy
